# Generated by Django 5.2.7 on 2025-11-01 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_Cadastro',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('limite_produto', models.IntegerField()),
                ('qtd_atual', models.IntegerField()),
            ],
            options={
                'db_table': 'Produto_Cadastro',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_movimentacao', models.DateTimeField()),
                ('entrada_saida', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('qtd_movimentacao', models.IntegerField()),
                ('id_produto_fk', models.ForeignKey(db_column='ID_Produto_FK', on_delete=django.db.models.deletion.CASCADE, to='estoque.produto_cadastro')),
                ('id_usuario_fk', models.ForeignKey(db_column='ID_Usuario_FK', on_delete=django.db.models.deletion.CASCADE, to='estoque.usuario')),
            ],
            options={
                'db_table': 'Movimentacao',
            },
        ),
    ]
